apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-neo4j-backup
spec:
  schedule: {{ default "0 3 * * *" .Values.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: neo4j-backup
              image: neo4j:5.2-enterprise
              command:
                - "/bin/bash"
                - "-c"
                - |
                  set -e
                  if [ ! -d "/mnt/backups/{{ required "Name must provided" .Values.name }}" ]; then
                    mkdir /mnt/backups/{{ .Values.name }}
                  fi
                  old_IFS=$IFS
                  IFS=','
                  db_names="{{- join "," .Values.databases }}"
                  for db in $db_names; do
                    neo4j-admin database backup \
                    --from={{ required "Backup service must be provided" .Values.service }} \
                    --to-path=/mnt/backups/{{ .Values.name }} \
                    --verbose $db
                  done
                  IFS=$old_IFS
              volumeMounts:
                - name: shared-volume
                  mountPath: /mnt/backups
                  readOnly: false
              resources:
                limits:
                  cpu: {{ default "200m" .Values.resources.cpu }}
                  memory: {{ default "800Mi" .Values.resources.memory }}
          containers:
            - name: gcs-fuse
              image: shubham030/gcs-fuse
              command:
                - "/bin/sh" 
                - "-c"
                - |
                  echo {{ required "Service Account is required" .Values.serviceAccount }} | base64 -d > /etc/gcloud/service-account.json
                  gcsfuse {{ required "Bucket name must be provided" .Values.bucket }} /mnt/gcs
                  mv /mnt/backups/* /mnt/gcs/
              volumeMounts:
                - name: gcs-creds-volume
                  mountPath: /etc/gcloud
                - name: shared-volume
                  mountPath: /mnt/gcs
                - name: shared-volume
                  mountPath: /mnt/backups
              securityContext:
                privileged: true
          restartPolicy: {{ default "OnFailure" .Values.restartPolicy }}
          volumes:
            - name: shared-volume
              emptyDir: {}
            - name: gcs-creds-volume
              emptyDir: {}
