apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-state
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.state.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.state.size }}
